language: generic

sudo: required
services:
    - docker
    
before_install:
    - docker build -t cimedia/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true cimedia/docker-react npm run test
  
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-590934922961"
    backet_path: "docker-react"
    on:
        branch: master